exes/confman/CMakeLists.txt
exes/confman/src/main.cpp
libs/confman/CMakeLists.txt
libs/confman/inc/public/tfc/confman/detail/common.hpp
libs/confman/inc/public/tfc/confman/detail/config_rpc_server.hpp
libs/progbase/CMakeLists.txt
libs/progbase/inc/public/tfc/progbase.hpp
libs/progbase/src/progbase.cpp

- simple confman executable
- make confman config file as cli arg

16 create confman executable

---

exes/operation-mode/CMakeLists.txt
exes/operation-mode/inc/app_operation_mode.hpp
exes/operation-mode/inc/state_machine.hpp
exes/operation-mode/src/app_operation_mode.cpp
exes/operation-mode/src/state_machine.cpp
exes/operation-mode/tests/CMakeLists.txt
exes/operation-mode/tests/operation_mode_integration_test.cpp
libs/confman/CMakeLists.txt
libs/confman/inc/public/tfc/confman/remote_change.hpp
libs/confman/src/remote_change.cpp
libs/operation_mode/inc/public/tfc/operation_mode/common.hpp
libs/operation_mode/src/operation_mode.cpp
libs/stx/inc/public/tfc/stx/glaze_meta.hpp

Operation mode should be working, however, a better test suite would be nice. Defer after ipc mocks has been done.

Tidy up operation mode

---

libs/ipc/inc/public/tfc/ipc/details/dbus_server_iface.hpp
libs/operation_mode/inc/public/tfc/operation_mode.hpp
libs/operation_mode/src/operation_mode.cpp

sdbusplus match cannot be moved within object

---

.github/workflows/docs.yml

relates to this https://github.com/actions/upload-pages-artifact/pull/54
as said, fixed in v1.0.7

fix docs upload

---

libs/confman/testing/CMakeLists.txt
libs/confman/testing/examples/CMakeLists.txt
libs/confman/testing/examples/array.cpp
libs/confman/testing/examples/nested.cpp
libs/confman/testing/examples/simple.cpp
libs/confman/testing/examples/variant.cpp

should this be in the repo or not? if in repo should it be add to example docs?

Confman examples for frontend

---

docs/doxygen.rst
docs/index.rst

Fixing docs

---

cockpit/IPC/install/create_link.js

Trying to make create_link more robust

---

cockpit/IPC/src/Components/Form/Form.tsx
cockpit/IPC/src/Components/Form/UnitsWidget.css
cockpit/IPC/src/Components/Form/UnitsWidget.tsx
cockpit/IPC/src/views/demoData.tsx

Form validation will fail if value is out of scope of min or max.
Fixes #168 
We should look into using this same system to verify required data, as of now, 'required' data can be left null and sent to DBUS.
We could implement this ourselves, however it would likely be easier to use UI-Schema's built in validation feature.
To do this we simply need to implement #172

Initial fix for min and max.

---

CMakeLists.txt
cmake/tfc_options.cmake
examples/CMakeLists.txt
examples/test_rig/CMakeLists.txt
examples/test_rig/main.cpp
exes/ethercat/inc/public/tfc/ec/devices/abt/easycat.hpp
exes/ethercat/inc/public/tfc/ec/devices/abt/firmware/firmware.ino
exes/ethercat/inc/tfc/ec/devices/beckhoff/EL1xxx_impl.hpp

Would we like this code checked in?

Presentation

---

exes/ethercat/inc/public/tfc/ec/devices/base.hpp
exes/ethercat/inc/public/tfc/ec/devices/beckhoff/EL1xxx.hpp
exes/ethercat/inc/public/tfc/ec/devices/device.hpp
exes/ethercat/inc/tfc/ec/devices/beckhoff/EL1xxx_impl.hpp
exes/ethercat/src/devices/beckhoff.cpp
exes/ethercat/tests/devices/beckhoff.cpp

todo refactor interpretation of buffer

On the spot el1809 driver

---

exes/gpio/src/gpio.cpp
libs/confman/inc/public/tfc/confman/observable.hpp
libs/confman/testing/tests/confman_test.cpp
libs/confman/testing/tests/confman_unit_test.cpp
libs/confman/testing/tests/file_storage_test.cpp
libs/confman/testing/tests/observer_test.cpp

Embeded observable callback was erased during from_json parsing by a copy
Co-authored-by: Jón Bjarni Bjarnason <jon.bjarni@skaginn3x.com>

Embeded observable callback

---

exes/mqtt-broadcaster/inc/config.hpp
libs/stx/inc/public/tfc/stx/glaze_meta.hpp
libs/stx/inc/public/tfc/utils/json_schema.hpp
libs/stx/inc/public/tfc/utils/units_glaze_meta.hpp
libs/stx/inc/public/tfc/utils/uuids_glaze_meta.hpp

glz meta fixes

---

cockpit/IPC/src/Components/Table/SlotModal.tsx
cockpit/IPC/src/Components/Table/Table.tsx
cockpit/IPC/src/Components/Table/TableItems/EmptyState.tsx
cockpit/IPC/src/Components/Table/Toolbar.css
cockpit/IPC/src/Components/Table/Toolbar.tsx
cockpit/IPC/src/Components/Table/ToolbarItems/MultiSelectAttribute.tsx
cockpit/IPC/src/Components/Table/ToolbarItems/TextBoxAttribute.tsx

Changed Filter processes to be a list

---

libs/ipc/inc/public/tfc/ipc.hpp
libs/ipc/inc/public/tfc/ipc/details/dbus_ipc.hpp

should be faster and does not depend on async operations

using last value cache from dbus instead of internal state

---

cockpit/IPC/src/Components/Table/FilterModal.tsx

Fixing Filter Modal in Connections view

---

cockpit/IPC/src/views/Connections.tsx

Added keyboard shortcut information to a modal in Connections.

Added keyboard shortcut information to connections

---

cockpit/IPC/src/Components/Table/Table.tsx
cockpit/IPC/src/views/Connections.tsx

If locale is Iceland
If locale is Los Angeles

Added timezone compensation and formatting to Connections view

---

cockpit/IPC/src/Components/Form/Form.tsx
cockpit/IPC/src/Components/Form/VariantWidget.tsx
cockpit/IPC/src/Components/Form/WidgetFunctions.tsx
cockpit/IPC/src/Components/Table/FilterModal.tsx
cockpit/IPC/src/views/Configurator.tsx
libs/ipc/inc/public/tfc/ipc/details/filter.hpp
libs/stx/inc/public/tfc/utils/json_schema.hpp

Fixing selection, looking into invert filter

---

exes/ethercat/inc/public/tfc/cia/402.hpp
exes/ethercat/inc/public/tfc/ec/devices/schneider/atv320.hpp
exes/ethercat/inc/public/tfc/ec/devices/util.hpp
exes/ethercat/tests/test_ec_402.cpp
exes/ethercat/tests/test_ec_util.cpp

* Map function made constexpr and moved tests to being compiled
* Map caps input value according to input value mappings
* Atv320 change input freq to input ratio with -100% to 100% range

atv320 ratio slot

---

exes/ethercat/CMakeLists.txt
exes/ethercat/systemd/ethercat@.service

ethercat binary path is slightly wrong in .service file for ethercat

ethercat path fixed to correct binary path

---

exes/ethercat/inc/public/tfc/ec/devices/schneider/atv320.hpp

ATV320 NPR off by a factor of 10

---

cockpit/IPC/src/App.tsx

Should fix white screen on load when using release.
This was an issue because the router assumed the folder it was being served from was "IPC" not "ipc" as the release called it.

Changed routing to hopefully fix release issues

---

cockpit/IPC/src/Components/Table/Table.tsx

Added filter for connection status

---

cockpit/IPC/src/Components/IOList/ListItem.tsx
cockpit/IPC/src/Components/Tinker/BoolTinker.tsx
cockpit/IPC/src/views/IODebug.tsx

fixes #258 
Added checkboxes to DebugUI to subscribe and unsubscribe from changes for that particular item.
@jbbjarnason Could you check if this reduces load?

Add checkbox to subscribe and unsubscribe from slots andn signals

---

cockpit/IPC/src/Components/Form/Form.tsx
cockpit/IPC/src/Components/Form/VariantWidget.tsx
cockpit/IPC/src/Components/Form/WidgetFunctions.tsx
cockpit/IPC/src/views/Configurator.tsx

Fix handling of nulls on DBUS
Error came up when dbus value was a non-nested straight null

Fixed null handling on dbus

---

cockpit/IPC/src/Components/Form/BoolWidget.tsx
cockpit/IPC/src/Components/Form/Form.tsx

Added Tooltip to Boolean in configurator.
Should also not render if boolean is a const.

Added description tooltip to Boolean Widget

---

cockpit/IPC/CMakeLists.txt
cockpit/IPC/src/App.tsx

Need help changing the CMakeLists file to allow for a build flag for DebuggingUI.
@jbbjarnason

Debugui build flag

---

cockpit/IPC/src/App.tsx
cockpit/IPC/src/Components/Form/ArrayWidget.tsx
cockpit/IPC/src/Components/Form/BoolWidget.tsx
cockpit/IPC/src/Components/Form/Form.tsx
cockpit/IPC/src/Components/Form/StringWidget.tsx
cockpit/IPC/src/Components/Form/UnitWidget.tsx
cockpit/IPC/src/Components/Form/VariantWidget.tsx
cockpit/IPC/src/Components/Simple/DarkModeContext.tsx
cockpit/IPC/src/Components/Table/FilterModal.tsx
cockpit/IPC/src/views/Configurator.tsx
cockpit/IPC/src/views/Connections.tsx
cockpit/IPC/src/views/IODebug.tsx
cockpit/IPC/src/views/ListDBUS.tsx
cockpit/IPC/src/views/StateMachine.tsx

This pull request introduces two key updates:
1. **ArrayWidget Enhancements:**
- Fixed an issue with item deletion to ensure smooth functionality.
- Added tooltips to the Add and Delete buttons for better user guidance.
2. **Dark Mode Context:**
- Implemented a new `DarkModeContext` to manage the dark mode theme.
- The `DarkModeProvider` uses the user's system preferences and local storage settings to determine the theme.
- **ArrayWidget:**
- The deletion logic has been refined to ensure items are removed correctly.
- Proper handling of `minItems` and `maxItems`
- Tooltips saying "Add Item" and "Remove Item" have been added to the respective buttons for clarity.
- **DarkModeProvider:**
- Utilizes `useMediaQuery` to align with system theme settings.
- Listens to local storage changes for …

ArrayWidget Improvements and Dark Mode Context Implementation

---

cockpit/IPC/src/Components/Form/ArrayWidget.tsx
exes/ethercat/inc/public/tfc/ec/devices/device.hpp
exes/ethercat/inc/public/tfc/ec/devices/eilersen/4x60a.hpp
exes/tfcctl/src/tfcctl.cpp
libs/confman/inc/public/tfc/confman/read_only.hpp

Eilersen device support

---

CMakePresets.json
cmake/tfc_install.cmake
libs/configure_options/.gitignore
libs/configure_options/CMakeLists.txt

Tested in sensor control branch in devices repo, did not fail once.

334 configure options lib stored in binary dir

---

exes/mqtt-bridge/inc/config/broker.hpp
exes/mqtt-bridge/inc/config/spark_plug_b.hpp

Add default values for mqtt bridge

---

exes/ethercat/inc/public/tfc/ec/devices/schneider/atv320/dbus-iface.hpp
exes/ethercat/tests/devices/atv320-dbus-iface-integration.cpp
libs/motor/inc/public/tfc/motor.hpp
libs/motor/inc/public/tfc/motor/atv320motor.hpp
libs/motor/inc/public/tfc/motor/dbus_tags.hpp
libs/motor/inc/public/tfc/motor/enums.hpp
libs/motor/inc/public/tfc/motor/virtual_motor.hpp
libs/motor/tests/example/motor_example.cxx

optional forward and backwards for run

Motor direction

---

CMakeLists.txt
exes/ethercat/CMakeLists.txt
libs/configure_options/CMakeLists.txt

yet to test on target, but I unpacked debians to verify locations

update cmake modules

---

libs/stx/inc/public/tfc/utils/json_schema.hpp
libs/stx/inc/public/tfc/utils/units_glaze_meta.hpp

Ban slashes in json schema defs aswell as remove them from mp units schema

---

libs/confman/inc/public/tfc/confman.hpp
libs/confman/inc/public/tfc/confman/file_storage.hpp
libs/confman/testing/mocks/inc/public/tfc/mocks/confman/file_storage.hpp
libs/confman/testing/stubs/inc/public/tfc/stubs/confman/file_storage.hpp
libs/confman/testing/tests/CMakeLists.txt
libs/confman/testing/tests/confman_test.cpp
libs/confman/testing/tests/file_descriptor_limit.cpp
libs/confman/testing/tests/file_storage_test.cpp
libs/logger/inc/custom_sink.hpp
libs/logger/inc/public/tfc/logger.hpp
libs/logger/src/logger.cpp
libs/logger/tests/logging_test.cpp

Key retained:
Secondly added source location support:

Reduce file descriptors

---

cockpit/src/views/Configurator.tsx

Items in sidebar are now sorted.
closes #354

Sorted config items in sidebar

---

libs/motor/inc/public/tfc/motor/details/positioner_impl.hpp
libs/motor/testing/tests/positioner_test.cpp
libs/stx/inc/public/tfc/utils/json_schema.hpp

const reflected in json schema of variant tags

---

libs/motor/inc/public/tfc/motor/stub.hpp
libs/motor/testing/tests/stub_test.cpp

Added stop methods and absolute positioning methods.

Motor stub

---

libs/motor/inc/public/tfc/motor/details/positioner_impl.hpp
libs/motor/inc/public/tfc/motor/errors.hpp
libs/motor/inc/public/tfc/motor/positioner.hpp
libs/motor/src/error.cpp
libs/motor/testing/tests/positioner_test.cpp

Todo make tests from video
Todo make error tests for positioner

detect different kind of encoder errors

---

cockpit/src/Components/Form/ArrayWidget.tsx
cockpit/src/Components/Form/UnitWidget.tsx
cockpit/src/views/Configurator.tsx

fixes #351 - Implementation might change
fixes #462 - Fixed "0" handling
changed implementation of #354 - Requires testing
This PR is a mixed bag of minor fixes
Current implementation of #351 looks slightly off, open to suggestions on alternative implementations

General Configurator fixes

---

cockpit/src/Components/Table/Table.tsx

Added copy icon to connections view

---

libs/ipc/inc/public/tfc/ipc/details/item_glaze_meta.hpp
libs/ipc/inc/public/tfc/ipc/item.hpp
libs/ipc/src/item.cpp

Added field last_exchange to item to indicate when the item last changed hands

Added field last_exchange to item

---

exes/operations/inc/details/state_machine_owner_impl.hpp

operations send default values on construction

---

containers/tfc-toolchain/tfc-toolchain.dockerfile
exes/ethercat/inc/public/tfc/ec/devices/beckhoff/EL4xxx.hpp
exes/ethercat/inc/public/tfc/ec/devices/eilersen/4x60a.hpp
exes/ethercat/inc/public/tfc/ec/devices/schneider/atv320.hpp
exes/ethercat/inc/public/tfc/ec/devices/schneider/lxm32m.hpp

I would like to reinterpret the buffer before calling process_data, what's your opinion on that @omarhogni ?

update toolchain to llvm 18
